In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from scipy.io import wavfile
from matplotlib import pyplot as plt
from PIL import Image

In [74]:
image1 = np.array(Image.open('./data/image1.png'))
image2 = np.array(Image.open('./data/image2.png'))
newimage = np.empty(image1.shape)
image11 = image1.flatten()
image22 = image2.flatten()
z = np.array([image11,image22])
eig = np.linalg.eig(np.cov(z))
D = eig[0]
E = eig[1]
D = np.sqrt(D)
D = 1/D
V = np.dot(np.dot(E,np.diag(D)),np.transpose(E))
newvar = np.dot(V,z)

wT = np.array([1,1]) #wの転置を定める
wT = wT/np.linalg.norm(wT)
w = wT.T
b = wT
preW = w
while(1):
  wT = w.T
  tmpw = np.dot(newvar,np.power(np.dot(wT,newvar),3))/(512*512)-3*w
  w = tmpw/np.linalg.norm(tmpw)
  if(np.isclose(w,preW).all() or np.isclose(w*(-1),preW).all()):
    break
  else:
    preW = w
print(w)
newimage = np.dot(w,newvar)
#-------------------------------#
wT = np.random.rand(2)
w = wT.T
b = wT
preW = w
while(1):
  wT = w.T
  tmpw = np.dot(newvar,np.power(np.dot(wT,newvar),3))/(512*512)-3*w
  w = tmpw/np.linalg.norm(tmpw)
  if(np.isclose(w,preW).all() or np.isclose(w*(-1),preW).all()):
    break
  else:
    preW = w

def min_max(x, axis=None):
    min = x.min(axis=axis, keepdims=True)
    max = x.max(axis=axis, keepdims=True)
    result = (x-min)*255/(max-min)
    return result

c = min_max(newimage)
print(c.shape)
c = c.reshape(512,512)
c = c.astype(np.uint8)
print(c)
print(image1)
Image.fromarray(c).save("./test2.png")

[0.76557979 0.64334096]
(262144,)
[[189 189 189 ... 140 116 104]
 [189 189 189 ... 135 125  95]
 [189 189 189 ... 136 121 106]
 ...
 [ 46  46  47 ... 146 146 144]
 [ 46  46  50 ... 143 143 143]
 [  0  46  50 ... 143 143 143]]
[[179 179 179 ... 133 113 104]
 [179 179 179 ... 129 121  97]
 [179 179 179 ... 130 117 106]
 ...
 [ 60  60  60 ... 145 146 144]
 [ 60  60  62 ... 142 142 142]
 [ 17  60  62 ... 142 142 142]]
